name: Build & Push to artifactory

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: build and push
        env:
          IMAGE_TAG: ${{ github.sha }}
          ARTIFACTORY_URL: zpitwitteranalysis.jfrog.io/zpi/client
          IMAGE_NAME: zpi-twitter-client
        run: |
            docker build -t $ARTIFACTORY_URL/$IMAGE_NAME:$IMAGE_TAG .
            docker push $ARTIFACTORY_URL/$IMAGE_NAME:$IMAGE_TAG 
            echo "Obraz zostal zbudowany i spushowany do: $ARTIFACTORY_URL/$IMAGE_NAME:$IMAGE_TAG"
          
