name: ZPI Twitter Client Mainline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-and-push-to-artifactory:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Artifactory
        uses: docker/login-action@v1 
        with:
          registry: zpitwitteranalysis.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: ${{ github.sha }}
          ARTIFACTORY_URL: zpitwitteranalysis.jfrog.io/zpi
          IMAGE_NAME: zpi-twitter-client
        with:
          push: true
          tags: $ARTIFACTORY_URL/$IMAGE_NAME:latest, $ARTIFACTORY_URL/$IMAGE_NAME:$IMAGE_TAG

