name: Build & Push to artifactory

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: build and push
        env:
          IMAGE_TAG: ${{ github.sha }}
          ARTIFACTORY_URL: zpitwitteranalysis.jfrog.io/zpi/client
        run: |
            docker build zpitwitteranalysis.jfrog.io/zpi/client/test:$IMAGE_TAG .
            docker push zpitwitteranalysis.jfrog.io/zpi/client/test:$IMAGE_TAG
          
